codecov:
  token: ebbeede2-d076-47fc-8b6c-9c90e4391cd3

coverage:
  precision: 2
  round: down
  range: "90...100"

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  behavior: default
