version: '3'

services:
  app: &app
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      .env
    command: ash -c "yarn workspace @mybot/example start"
  karma:
    <<: *app
    env_file:
      .env
    command: ash -c "yarn workspace @mybot/karma start"
