version: '3'

services:
  app: &app
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      .env
    command: ash -c "yarn workspace @mybot/example start"
  karma:
    <<: *app
    env_file:
      .env
    depends_on:
      - redis
    command: ash -c "yarn workspace @mybot/karma start"
  redis:
    image: "redis:alpine"
    ports:
      - "16379:6379"
    volumes:
      - "./data/redis:/data"
